### ISSUE TITLE
unwanted files after a failed download

### ISSUE THREAD

**Issue by rodrigoxmax** [gl00mm/Blasphemous_PSVITA#1]
When I downloaded the vpk and it failed I had less space than before and I deleted the vpk and I still have less space

**Comment by gl00mm** [comment]
If you had a crash (which is logical if you had only the vpk installed without the patched game files), then I guess you are mentioning the dump file that was created. 
Each crash you encounter on your vita creates a dump file that you can find under ux0:/data/psp2core-XXX. 
You can delete those files.
