### ISSUE TITLE
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by danfmsouza** [gl00mm/Blasphemous_PSVITA#2]
I was trying to generate BlasphemousVITA.zip but when xdelta3 is running I got the following error:

```
xdelta3: secondary compression: lzma
xdelta3: source BlasphemousDATA.zip source size 807 MiB [846362908] blksize 2.00 MiB window 64.0 MiB
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```

My Blasphemous version is the Digital Deluxe Edition with all DLCs. There is a way to avoid this checksum missmatch?

**Comment by gl00mm** [comment]
Hi, 

The patcher only works with the base edition of the game (including the 3 free big DLC’s but not the extra skin, ost and books). 
I’m sorry I don’t have the digital deluxe edition so I’m not able to create a patcher for it.

Is this possible for you to only have the base edition (either by downloading it, either by removing the 4 digital deluxe content) ?

**Comment by danfmsouza** [comment]
I tried removing all DLC from the Digital Deluxe Edition, and after that, I updated the game. When I did that, I was able to run xdelta3 successfully! Thanks, @gl00mm! I made some tests by removing most of the Vita plugins and overclocking both the CPU and GPU, achieving 28 to 30 FPS most of the time.
